name: Matterbridge-Home-Assistant
description: Populate your Home Assistant instance as Matter Bridge
slug: matterbridge_home_assistant
version: 0.0.4
image: ghcr.io/matterbridge-home-assistant:0.0.4
options:
  home_assistant_url: ""
  home_assistant_access_token: ""
  home_assistant_client_config: "{}"
schema:
  home_assistant_url: str
  home_assistant_access_token: str
  home_assistant_client_config: str
host_network: true
webui: http://[HOST]:[PORT:8283]/
init: false
arch:
  - amd64
  - armv7
