---
name: Deploy

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  workflows:
    permissions:
      packages: write
      contents: write
    uses: hassio-addons/workflows/.github/workflows/addon-deploy.yaml@main
    with:
      slug: "matterbridge"
      repository_edge: ${{ github.event.repository.name }}
      repository_beta: ${{ github.event.repository.name }}
      repository: ${{ github.event.repository.name }}
    secrets:
      DISPATCH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
